pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
    }
}

dependencyResolutionManagement {
    // Prefer project-level repositories but still allow global ones.
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)

    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }

        // Local AAR/JAR libs
        flatDir {
            dirs("${rootDir}/app/libs")
        }
    }
}

// Optional but improves Gradle sync performance
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "AliNajDemo"

include(":app")
